apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-bluegreen 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollout-bluegreen
        image: nginx:1.14.3
