apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gmharbor.com/poc/flask:1.0
  name: nginx-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-dep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
