apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-dep
  name: nginx-dep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dep
  type: LoadBalancer
