apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-config
spec:
  storageClassName: jupeterhub
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupeterhub1
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: jupeterhub
